### ISSUE TITLE
usher when run with an invalid parameter provides no feedback.

### ISSUE THREAD

**Issue by davidelliottfmp** [findmypast/usher#31]
IE
usher this-should-not-really-work

returns with no message.

**Comment by jbachhardie** [comment]
We are aware of this issue and it was in our backlog. I might take a minute this afternoon to fix it, thanks for the reminder.

**Comment by jbachhardie** [comment]
Fixed in 78b3813453f6ad70de7f3b055cb7f9d7c9d17998
